name: omg1
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  sqflite: ^2.0.0+4
  bloc: ^7.1.0
  flutter_bloc: ^7.1.0
  flutter_slidable: ^0.6.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/nodata.png
    - images/nodata2.png      
  fonts:
    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
        

    - family: Source Sans Pro Bold
      fonts:
        - asset: fonts/SourceSansPro-Black.ttf

    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans-Regular.ttf

    - family: Helvetica
      fonts:
        - asset: fonts/helvetica-heavy.ttf    

    
 
